name: Cache Docker 3rd Party Images

on:
  schedule:
    - cron: '0 0 1 * *' # trigger on the 1st of every month at midnight
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - # ghcr logins for pushing image after testing
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - # copy 3rd party zookeeper image from dockerhub to quay and ghcr
        name: Push Image to target registries
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: wurstmeister/zookeeper:latest
          dst: |
            ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/3rdparty/zookeeper:latest
      - # copy 3rd party kafka image from dockerhub to quay and ghcr
        name: Push Image to target registries
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: wurstmeister/kafka:latest
          dst: |
            ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/3rdparty/kakfa:latest
