name: Cache Docker 3rd Party Images

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - # ghcr logins for pushing image after testing
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - # copy multiplatform image from dockerhub to quay and ghcr
        name: Push Image to target registries
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/paulyuk/kafka:latest
          dst: |
            ghcr.io/paulyuk/paulyuk:latest
