name: Validate go sdk

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - feature/new_quickstarts
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - master
      - feature/new_quickstarts
      - release-*
jobs:
  deploy:
    name: Validate quickstarts on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      DAPR_INSTALL_URL: https://raw.githubusercontent.com/dapr/cli/master/install
      GOVER: 1.17
      KUBERNETES_VERSION: v1.21.1
      KIND_VERSION: v0.11.0
      KIND_IMAGE_SHA: sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
    strategy:
      matrix: 
        os: [ubuntu-latest]
      fail-fast: false
    steps: 
      - name: Validate bindings go http
        run : |
          pushd bindings/go/http
          make validate
          popd
      - name: Validate bindings go sdk
        run : |
          pushd bindings/go/sdk
          make validate
          popd
      - name: Validate configuration go http
        run : |
          pushd configuration/go/http
          make validate
          popd
      - name: Validate configuration go sdk
        run : |
          pushd configuration/go/sdk
          make validate
          popd
      - name: Validate pub_sub go http
        run : |
          pushd pub_sub/go/http
          make validate
          popd
      - name: Validate pub_sub go sdk
        run : |
          pushd pub_sub/go/sdk
          make validate
          popd
      - name: Validate resiliency go http
        run : |
          pushd resiliency/go/http
          make validate
          popd
      - name: Validate resiliency go sdk
        run : |
          pushd resiliency/go/sdk
          make validate
          popd
      - name: Validate secrets_management go http
        run : |
          pushd secrets_management/go/http
          make validate
          popd
      - name: Validate secrets_management go sdk
        run : |
          pushd secrets_management/go/sdk
          make validate
          popd
      - name: Validate service_invocation go http
        run : |
          pushd service_invocation/go/http
          make validate
          popd
      - name: Validate service_invocation go sdk
        run : |
          pushd service_invocation/go/sdk
          make validate
          popd
      - name: Validate state_management go http
        run : |
          pushd state_management/go/http
          make validate
          popd
      - name: Validate state_management go sdk
        run : |
          pushd state_management/go/sdk
          make validate
          popd